# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: sy0227
email: sy0227@naver.com

#write html inside the double quotes to display in jumbotron
description: "<h3>Welcome!</h3><h1>Suyeon's blog</h1><h3>Hope you like it!</h3>"



baseurl: / # the subpath of your site, e.g. /blog
url: "http://sy0227.github.io" # the base hostname & protocol for your site


# Build settings
markdown: kramdown
